### PR TITLE
Fixed spec_helper requirements *removed comment

### PR DESCRIPTION
**Pull request by hamin**
you can now run rake spec properly to run all specs

### CODE REVIEW

**Comment by hamin** [comment]
i also added the GetQualificationRequests API, specs pass and I just tested it with a personal account and it seems to be working properly, if you could pull that in that would be great :)

**Comment by dbalatero** [comment]
Ok, I'd prefer you to separate pull requests out if they are not directly related to one another. It makes it way harder for me to deal with a pull request with many different things (and increases the likelihood I won't merge it, due to possible work needed on any of the N features).

One branch per feature! Thanks!

**Comment by hamin** [comment]
hey david,

Sorry I actually didn't realize that the GetQualificationRequests commit would get added to the Pull Request automatically. How do I remove that commit for the pull request and then submit a new pull request for that new feature?

Thanks

**Comment by dbalatero** [comment]
Doesn't matter, I merged both.

You should develop each feature on a separate branch, and set a pull request from each branch. Otherwise, every new commit you add to master gets added to the pull request.

**Comment by hamin** [comment]
Ah, I see David. Thanks, will do that next time. I'll be working on GrantQualification call soon so I'll work on it the way you suggested. Thanks for merging it in :)

**Pull request closed without merging**
