### PR TITLE
Grant qualification

### PR DESCRIPTION
**Pull request by hamin**
Added GrantQualification API, which grants a Worker's request for a Qualification.

### CODE REVIEW

**Comment by hamin** [comment]
hmm..sorry i created a new branch for the feature and sent a pull request from github while switched to that branch, its still pulling old commits for the pull request...a bit confused here

**Comment by mdp** [comment]
Hey, thanks for adding this. I'm going to work on getting these in tonight. I've got another branch where I'm updating to rspec2, aptly named 'rspec2'. The tests are passing, so I'll merge in your changes, and then merge into master tonight.

**Comment by hamin** [comment]
cool...no worries... i have another pull request on the way with specs, if u could add that too that would be great

**Comment by dbalatero** [comment]
I'm a moron, I merged these with the fork queue. I'm going to undo that, hold tight.

**Comment by dbalatero** [comment]
Undo'd. Mark, you'll merge these in then?

**Comment by mdp** [comment]
Yeah, this is all in 2.3.6 and pushed to gemcutter.

**Comment by hamin** [comment]
Awesome :) thanks

**Pull request merged**
