### PR TITLE
various improvements to rturk

### PR DESCRIPTION
**Pull request by alexch**
Thanks for your work on RTurk! I just did a project that would have taken 3x as long without it. Along the way I made my own fork -- god bless Github -- and added some features and cleaned up some stuff. Please take a look at this and let me know what you think. If you want to accept some of my patches and reject others, let me know and I'll make separate branches for you and send separate pull requests from them.

Here's a summary of my important changes:

Feature: allow "internal questions" aka QuestionForms

API: renamed several fields to be more consistent, either between rturk and the "real" XML field names, or between rturk request and rturk response objects

Bug: make sure to use UTC in timestamp (at least I thought it was a bug -- my issue may have been caused by something else, but this cleanup seems harmless at worst)

Dev:
use RSpec 2
replace unpacked aws_docs html with a tarball that you can unpack if you like

I've only tested it under Ruby 1.9.2 so beware of that. And again, I'm more than happy to discuss these changes, and willing to change them as you see fit in order to get at least some of them merged into the mainline.

Also, I've got a nascent QuestionForm erector widget, so you can build QuestionForms with code like this:
https://gist.github.com/1031839
Not sure what you want to do with it but I think it's pretty cool. :-)

Here's the commit summary:

b815781 Alex Chaffee 26 hours ago use tap instead of inject to build an array (higher performance, cleaner code)
827db16 Alex Chaffee 2 days ago rename 'auto_approval' to 'auto_approval_delay' for consistency
a304d41 Alex Chaffee 2 days ago don't swallow method_missing
e9b6c2d Alex Chaffee 2 days ago nevermind
6fb7885 Alex Chaffee 2 days ago operations stash their RestClient response, for debugging
3a1d6ee Alex Chaffee 2 days ago rename 'assignments' accessor/mutator to 'max_assignment' for consistency with its real name (MaxAssignments) and to remove confusion between it and the other property named 'assignments'
dd1ffba Alex Chaffee 2 days ago rename 'note' to 'annotation' for consistency with response and with its real name (RequesterAnnotation)
50acfab Alex Chaffee 2 days ago use UTC and ISO8601 format for the timestamp
13ec87d Alex Chaffee 2 days ago brief docs for QuestionForm feature
5b16995 Alex Chaffee 4 days ago updated gemspec
fac09b1 Alex Chaffee 4 days ago QuestionForm (aka Internal Question) and a new question_form setter on the CreateHIT operation
1f89de7 Alex Chaffee 4 days ago rename Question to ExternalQuestion
0409d63 Alex Chaffee 4 days ago minor cleanup to rdoc task
5417590 Alex Chaffee 4 days ago Change aws_docs to a tarball so they don't clutter up search results. Unpack them if you want them; the directory is now gitignored so you won't accidentally check them in.
d3da97a Alex Chaffee 4 days ago update to use RSpec 2

### CODE REVIEW

**Comment by mdp** [comment]
Hey Alex, thanks for the pull request. It looks like you've got some pretty good stuff in there.

I'll need to test this on Ruby 1.8.7, since I'd like to keep it compatible.

As for the renaming, I'd like to get this in here at some point, especially the 'assignments' due to ambiguity, but it's going to break backwards compatibility. If we're going to do that, I'd like to get your QuestionForm builder in there fully and then bump the major version for a good reason.

I'll cherry pick out the bug fixes and dev updates and get that going in v2.4.1. Can you get your QuestionForm class in there and we can take a look at it?

**Comment by alexch** [comment]
https://github.com/alexch/rturk/commit/b67551127e44c10b8a9ab188cdd2822fa4fe532d has the new QuestionForm and AnswerKey builders. The API is a little spotty and needs some sample code but it should work OK under the hood.

Note that I'm using a prerelease version of Erector but it'll be stable enough to ship with, if you so desire.

**Comment by ghost** [comment]
What's the status of this pull request?  Is the code in alexch's fork being maintained?

**Comment by bluemont** [comment]
Who needs 1.8.7 support? In my case, the best libraries I'm using (Rails, Mongoid) have dropped 1.8.x support.

**Comment by mdp** [comment]
Plenty of people are still on 1.8.7, especially when your talking about a service as old as Mechanical Turk, and it's not terribly hard to maintain backwards compatibility.

As for this branch, it breaks some API compatibility, so I've been merging in smaller changes into 2.x and meaning to get this out to 3.x

That being said, I'm not actively using MechanicalTurk/rturk so it's been on my back burner. Would be happy if someone that uses it more wants to take it over. MechanicalTurk seems to be on the back burner for Amazon as well these days.

**Comment by cantino** [comment]
Hey @alexch, do you have any sample code showing how to create a HIT using QuestionForms?  (Also, long time no see!)

**Pull request closed without merging**
